---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Lambda Scala Example
Parameters:
  Version:
    Description: Lambda version
    Type: String
  LambdaName:
    Description: Name of the Lambda function
    Type: String
  Environment:
    Description: Name of the environment in which the stack is provisioned eg&#58; prod/dev
    Type: String
  AlarmSubscriptionEndpoint:
    Description: SNS subscription endpoint for cloudwatch alarm alerts
    Type: String
  AlarmSubscriptionProtocol:
    Description: SNS subscription protocol for cloudwatch alarm alerts
    Type: String

Resources:

  ###
  ### Lambda Resources
  ###

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: "../../../build/distributions/aws-lambda-scala.zip"
      Description: AWS Lambda Scala Example
      FunctionName: !Ref LambdaName
      Handler: tekumara.Lambda
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: java8
      Timeout: 10
      ReservedConcurrentExecutions: 10
      DeadLetterConfig:
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          version: !Ref Version
          environment: !Ref Environment

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaIAMPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroup}:*"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt DeadLetterQueue.Arn

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaName}"
      RetentionInDays: 30

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${LambdaName}-dead-letter"
      # retain for 14 days
      MessageRetentionPeriod: 1209600

  AlarmSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${Environment}: ${LambdaName} alarm topic"
      Subscription:
        - Endpoint: !Ref AlarmSubscriptionEndpoint
          Protocol: !Ref AlarmSubscriptionProtocol

  ###
  ### Alarms
  ###

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if number of lambda invocation errors grow beyond [Threshold] within [Period]"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref LambdaName
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 10
      TreatMissingData: notBreaching
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic

  LambdaHeartBeatAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarms if the lambda hasn't run"
      Namespace: "AWS/Lambda"
      MetricName: "Invocations"
      Dimensions:
        - Name: "FunctionName"
          Value: !Ref LambdaName
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 30
      Threshold: 1
      TreatMissingData: breaching
      ComparisonOperator: "LessThanThreshold"
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic

  DeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if number of dead letter message grow beyond [Threshold] within [Period]"
      Namespace: "AWS/SQS"
      MetricName: "ApproximateNumberOfMessagesVisible"
      Dimensions:
        - Name: "QueueName"
          Value:
            Fn::GetAtt:
              - "DeadLetterQueue"
              - "QueueName"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic
